"""upgrade columns in  Users

Revision ID: 318e177a61a6
Revises: e1e08fae755e
Create Date: 2024-04-25 19:02:17.098218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '318e177a61a6'
down_revision: Union[str, None] = 'e1e08fae755e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pagination', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pagination')
    # ### end Alembic commands ###
