"""upgrade table Users

Revision ID: e1e08fae755e
Revises: c9756e3aab91
Create Date: 2024-04-25 18:13:48.276974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1e08fae755e'
down_revision: Union[str, None] = 'c9756e3aab91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'subscription',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'subscription',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
